name: workflow 1 martín


on: 
  push : 
    branches: [main]
  pull_request : 
    branches: [main]

jobs:
  imprimir_info:  
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4

      - name: Imprimir Mensaje Personalizado
        
        run: |
          echo "Hola, soy Martín Rodríguez y este es mi primer workflow!"  
          echo "La fecha y hora actual es: $(date)"  

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9" 

      - name: Ejecutar script Python
        run: |
          mkdir build_output
          python3.12 my_script.py > build_output/output.txt

        
      - name: Subir artefactos construidos
        uses: actions/upload-artifact@v4
        with: 
          name: script_output
          path: build_output